import applicants_details_arrow from './applicants_details_arrow.svg';
import applicants_list_progressbar from './applicants_list_progressbar.svg';
import applicants_list_search from './applicants_list_search.svg';
import applicants_shift_left from './applicants_shift_left.svg';
import applicants_shift_right from './applicants_shift_right.svg';
import login_schedule_background from './background.svg';
import footer_facebook from './footer_facebook.svg';
import footer_github from './footer_github.svg';
import entry_logo from './entry_logo.svg';
import login_display from './login_display.svg';
import login_hide from './login_hide.svg';
import schedule_modify_application from './schedule_modify_application.svg';
import schedule_modify_interview from './schedule_modify_interview.svg';
import schedule_modify_presentation_registration from './schedule_modify_presentation_registration.svg';
import schedule_modify_presentation from './schedule_modify_presentation.svg';
import schedule_modify_shift from './schedule_modify_shift.svg';

export const details_arrow = applicants_details_arrow;
export const list_progressbar = applicants_list_progressbar;
export const search_icon = applicants_list_search;
export const shift_left_icon = applicants_shift_left;
export const shift_right_icon = applicants_shift_right;
export const background = login_schedule_background;
export const facebook_icon = footer_facebook;
export const github_icon = footer_github;
export const logo = entry_logo;
export const display_icon = login_display;
export const hide_icon = login_hide;
export const application_icon = schedule_modify_application;
export const interview_icon = schedule_modify_interview;
export const presentation_regiester_icon = schedule_modify_presentation_registration;
export const presentation_icon = schedule_modify_presentation;
export const schedule_shift_icon = schedule_modify_shift;
